[workspace]
members = [
    "BitVMX-CPU/bitcoin-script-riscv",
    "BitVMX-CPU/definitions",
    "BitVMX-CPU/emulator",
    "rust-bitcoin-coordinator",
    "rust-bitcoin-indexer",
    "rust-bitcoind",
    "rust-bitvmx-bitcoin-rpc",
    "rust-bitvmx-broker",
    "rust-bitvmx-client",
    "rust-bitvmx-job-dispatcher/dispatcher",
    "rust-bitvmx-job-dispatcher/emulator-dispatcher",
    "rust-bitvmx-job-dispatcher/jobtypes",
    "rust-bitvmx-job-dispatcher/risczero-dispatcher",
    "rust-bitvmx-job-dispatcher/dispatcher-utils",
    "rust-bitvmx-job-dispatcher/aws-helper",
    "rust-bitvmx-job-dispatcher/test-helper",
    "rust-bitvmx-key-manager",
    "rust-bitvmx-protocol-builder",
    "rust-bitvmx-settings",
    "rust-bitvmx-storage-backend",
    "rust-bitvmx-transaction-monitor",
    "rust-bitvmx-wallet",
    "rust-bitvmx-zk-proof/zk-result",
    "rust-bitvmx-gc",
]
