name: Nightly Build

on:
  schedule:
    - cron: '03 15 * * *'

jobs:
  nightly:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        submodule: [rust-p2p-protocol, rust-p2p-handler, rust-bitvmx-transaction-monitor, rust-bitvmx-transaction-dispatcher, rust-bitvmx-protocol-builder,
         rust-bitvmx-key-manager, rust-bitvmx-client, rust-bitcoin-indexer, rust-bitcoin-coordinator, BitVMX-cpu]
    steps:
      - name: Set up SSH key for submodule cloning
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up git with token authentication
        run: |
          git config --global url."https://${{ secrets.REPO_ACCESS_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Checkout workspace repository
        run: |          
          git clone --recurse-submodules --depth=1 --shallow-submodules https://github.com/FairgateLabs/rust-bitvmx-workspace rust-bitvmx-workspace

      - name: Call reusable workflow
        uses: ./rust-bitvmx-workspace/.github/workflows/test_template.yml@main  # or @your-branch
        with:
          repo: 'FairgateLabs/rust-bitvmx-workspace'
          submodule_path: ${{ matrix.submodule }}
          cargo_lock_path: '${{ matrix.submodule }}/Cargo.lock'
          target_path: '${{ matrix.submodule }}/target'