name: 'Set up and checkout repositories'
on:
  workflow_call:
    inputs:
      repo: 
        description: 'Repository to check out'
        required: true
        type: string
      submodule_path:
        description: 'Path to the submodule within the repository'
        required: true
        type: string
      cargo_lock_path:
        description: 'Path to the Cargo.lock file'
        required: true
        type: string
      target_path:
        description: 'Path to the target directory'
        required: true
        type: string
    secrets:
      REPO_ACCESS_TOKEN:
        description: 'Token to access the repository'
        required: true

jobs:
  test:
    if: ${{ !contains(github.event.pull_request.title, '[cov]') }}
    runs-on: ubuntu-latest
    steps: 
      - name: Set up git with token authentication
        run: |
          git config --global url."https://${{ secrets.REPO_ACCESS_TOKEN }}@github.com/".insteadOf "https://github.com/"
    
      - name: Checkout workspace repository
        run: |
          git clone --recurse-submodules --depth=1 https://github.com/${{ inputs.repo }} rust-bitvmx-workspace
      
      - name: Checkout current repository
        run: |
          BRANCH="${{ github.head_ref }}"
          if [[ -z "$BRANCH" ]]; then
            BRANCH="main"
          fi
          git clone --depth=1 --branch $BRANCH https://github.com/FairgateLabs/${{ inputs.submodule_path }} ${{ inputs.submodule_path }}
          ls -l ${{ inputs.submodule_path }}