name: 'Set up and checkout repositories'
on:
  workflow_call:
    inputs:
      repo: 
        description: 'Repository to check out'
        required: true
        type: string
      submodule_path:
        description: 'Path to the submodule within the repository'
        required: true
        type: string
      cargo_lock_path:
        description: 'Path to the Cargo.lock file'
        required: true
        type: string
      target_path:
        description: 'Path to the target directory'
        required: true
        type: string
    secrets:
      REPO_ACCESS_TOKEN:
        description: 'Token to access the repository'
        required: true
      SSH_PRIVATE_KEY:
        description: 'Private SSH key to authenticate with GitHub'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: Set up SSH key for submodule cloning
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | sed '1s/$/\n/' | sed 's/\(-----BEGIN OPENSSH PRIVATE KEY-----\)/\1\n/' | sed 's/\(-----END OPENSSH PRIVATE KEY-----\)/\n\1/' | tr -d '\n' | sed 's/\(-----BEGIN OPENSSH PRIVATE KEY-----\)\(.*\)\(-----END OPENSSH PRIVATE KEY-----\)/\1\2\3/' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Set up git with token authentication
        run: |
          git config --global url."https://${{ secrets.REPO_ACCESS_TOKEN }}@github.com/".insteadOf "https://github.com/"
    
      - name: Checkout workspace repository
        run: |
          rm -rf rust-bitvmx-workspace
          git clone --recurse-submodules --depth=1 --shallow-submodules https://github.com/${{ inputs.repo }} rust-bitvmx-workspace
      
      - name: Checkout current repository
        run: |
          BRANCH="${{ github.head_ref }}"
          if [[ -z "$BRANCH" ]]; then
            BRANCH="main"
          fi
          git clone --depth=1 --branch $BRANCH https://github.com/FairgateLabs/${{ inputs.submodule_path }} ${{ inputs.submodule_path }}
          ls -l ${{ inputs.submodule_path }}
