name: 'Local Test Action'
on:
  workflow_call:
    inputs:
      repo: 
        description: 'Repository to check out'
        required: true
        type: string
      submodule_path:
        description: 'Path to the submodule within the repository'
        required: true
        type: string
      cargo_lock_path:
        description: 'Path to the Cargo.lock file'
        required: true
        type: string
      target_path:
        description: 'Path to the target directory'
        required: true
        type: string
    secrets:
      REPO_ACCESS_TOKEN:
        description: 'Token to access the repository'
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  setup:
    uses: FairgateLabs/rust-bitvmx-workspace/.github/workflows/common_steps.yml@local_test_workflow
    with:
      repo: ${{ inputs.repo }} 
      submodule_path: ${{ inputs.submodule_path }}
      cargo_lock_path: ${{ inputs.cargo_lock_path }}
      target_path: ${{ inputs.target_path }}
    secrets: inherit
  
  setup-post-checkout:
    runs-on: ubuntu-latest
    container:
      image: fairgatelabs/rust-bitvmx-workspace:latest
    needs: setup
    steps:
      - name: Detect host for container
        run: |
          if (grep -qi microsoft /proc/version || docker info 2>/dev/null | grep -qi 'ostype: windows'); then
            echo "IS_WINDOWS_DOCKER=true" >> $GITHUB_ENV
          else
            echo "IS_WINDOWS_DOCKER=false" >> $GITHUB_ENV
          fi

      - name: Move all submodules to correct location
        if: env.ACT == 'true'
        run: |
          if [[ "$IS_WINDOWS_DOCKER" == "true" ]]; then
            find /mnt/c/rust-bitvmx-workspace/${{ inputs.submodule_path }}/${{ inputs.submodule_path }} -mindepth 1 -maxdepth 1 ! -name '${{ inputs.submodule_path }}' -exec mv {} /mnt/c/${{ inputs.submodule_path }}/ \;
          else
            find ${{ inputs.submodule_path }}/rust-bitvmx-workspace -mindepth 1 -maxdepth 1 ! -name '${{ inputs.submodule_path }}' -exec mv {} ${{ inputs.submodule_path }}/ \;
          fi
  
  build-test:
    uses: FairgateLabs/rust-bitvmx-workspace/.github/workflows/common_steps2.yml@local_test_workflow
    with:
      repo: ${{ inputs.repo }} 
      submodule_path: ${{ inputs.submodule_path }}
      cargo_lock_path: ${{ inputs.cargo_lock_path }}
      target_path: ${{ inputs.target_path }}
      docker_required: true
      dockerfile_path: src/tests/Dockerfile
      docker_compose_path: src/tests/docker-compose.yml
