name: 'Template Test Action'
on:
  workflow_call:
    inputs:
      repo: 
        description: 'Repository to check out'
        required: true
        type: string
      submodule_path:
        description: 'Path to the submodule within the repository'
        required: true
        type: string
      cargo_lock_path:
        description: 'Path to the Cargo.lock file'
        required: true
        type: string
      target_path:
        description: 'Path to the target directory'
        required: true
        type: string
      docker_required:
        description: 'Whether to execute Docker-related steps'
        required: false
        type: boolean
        default: false
      dockerfile_path:
        description: 'Path to Docker file'
        required: false
        type: string        
      docker_compose_path:
        description: 'Path to docker-compose file'
        required: false
        type: string
      nightly:
        description: 'Flag to determine if nightly triggered'
        required: false
        type: boolean
    secrets:
      REPO_ACCESS_TOKEN:
        description: 'Token to access the repository'
        required: true
      SSH_PRIVATE_KEY:
        description: 'Private SSH key to authenticate with GitHub'
        required: true
      SLACK_WEBHOOK_URL:
        description: 'Webhook endpoint to post on channel'
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ROOT: "/home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}"
      REPO_NAME: ${{ github.event.repository.name }}
      BRANCH: ${{ github.head_ref || 'main' }}

    steps:
      # Validate Inputs
      - name: Validate Inputs
        run: |
          if [[ -z "${{ inputs.repo }}" ]]; then
            echo "Error: 'repo' input cannot be empty."
            exit 1
          fi
          if [[ -z "${{ inputs.submodule_path }}" ]]; then
            echo "Error: 'submodule_path' input cannot be empty."
            exit 1
          fi
      
      - name: Cleanup Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf ~/Library/Caches
            
      # Check disk space
      - name: Check disk space
        run: df -h

      # Set up SSH for submodule cloning
      - name: Configure SSH for Git Submodule Access
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Set up git with token authentication
      - name: Configure Git with Token Authentication
        run: |
          git config --global url."https://${{ secrets.REPO_ACCESS_TOKEN }}@github.com/".insteadOf "https://github.com/"
     
      # Checkout workspace repository
      - name: Checkout Workspace Repository
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          if [[ "$PR_TITLE" =~ ^\[(.*)\] ]]; then
            BRANCH="${BASH_REMATCH[1]}"
          else
            BRANCH="main"
          fi
          echo "Checking out repository: $REPO_NAME on branch: $BRANCH"
          git clone --recurse-submodules --depth=1 --branch $BRANCH --shallow-submodules https://github.com/${{ inputs.repo }} rust-bitvmx-workspace
      
      - name: Checkout current repository
        run: |
          echo "Checking out branch: $BRANCH"
          git clone --depth=1 --branch $BRANCH https://github.com/FairgateLabs/${{ inputs.submodule_path }} ${{ inputs.submodule_path }}

      # Nightly build submodule handling
      - name: Handle Submodules for Nightly Build
        run: |
          if [[ "$NIGHTLY" == "true" ]]; then
            echo "Rearranging submodules for build"
            cd "$ROOT/rust-bitvmx-workspace"
            for dir in */; do
              name="${dir%/}"
              if [[ "$name" != "${{ inputs.submodule_path }}" ]]; then
                echo "Moving $name to $ROOT"
                mv "$name" "$ROOT/"
              fi
            done
            echo "Moved all other submodules to top-level"
            rm -rf "$ROOT/rust-bitvmx-workspace"
          else
            echo "Running in submodule-triggered mode"
            find /home/runner/work/${{ inputs.submodule_path }}/${{ inputs.submodule_path }}/rust-bitvmx-workspace -mindepth 1 -maxdepth 1 ! -name '${{ inputs.submodule_path }}' -exec mv {} /home/runner/work/${{ inputs.submodule_path }}/${{ inputs.submodule_path }}/ \;
          fi
        env:
          NIGHTLY: ${{ inputs.nightly }}

      # Install Rust
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      # Cache Rust toolchain
      - name: Cache Rust Toolchain
        uses: actions/cache@v3
        with:
          path: |
            ~/.rustup
            ~/.cargo/bin
          key: ${{ runner.os }}-rustup-${{ hashFiles('**/rust-toolchain*') }}
          restore-keys: |
            ${{ runner.os }}-rustup-

      # Cache Cargo registry
      - name: Cache Cargo Registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      # Cache Git dependencies
      - name: Cache Git Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-git-${{ hashFiles('**/Cargo.lock') }}

      # Cache workspace target directory
      - name: Cache Workspace Target Directory
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-workspace-target-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-workspace-target-

      # Cache submodule target directory
      - name: Cache Submodule Target Directory
        uses: actions/cache@v3
        with:
          path: ${{ inputs.submodule_path }}/target
          key: ${{ runner.os }}-${{ inputs.submodule_path }}-target-
          restore-keys: |
            ${{ runner.os }}-${{ inputs.submodule_path }}-target-

      ############ DOCKER SETUP OPTIONAL STEPS ############      
      - name: Set up Docker Buildx
        if: ${{ inputs.docker_required }}
        uses: docker/setup-buildx-action@v2

      - name: Create cache directory
        if: ${{ inputs.docker_required }}
        run: mkdir -p /tmp/.buildx-cache

      - name: Cache Docker layers
        if: ${{ inputs.docker_required }}
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
              ${{ runner.os }}-buildx-

      - name: Build and push Docker image        
        if: ${{ inputs.docker_required }}
        uses: docker/build-push-action@v4
        with:
          run: |
            ls -l
            pwd
          context: ./${{ inputs.submodule_path }}
          file: ./${{ inputs.submodule_path }}/${{ inputs.dockerfile_path }}
          push: false  # Build locally
          tags: user/repository:latest          

      - name: Run docker-compose
        if: ${{ inputs.docker_required }}
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          context: ./
          compose-file: "./${{ inputs.submodule_path }}/${{ inputs.docker_compose_path }}"
      ############ END DOCKER OPTIONAL SETUP STEPS ############

      # Build project
      # - name: Build Project
      #   working-directory: ${{ inputs.submodule_path }}
      #   run: cargo build --verbose
      
      # Run tests
      - name: Run Tests
        working-directory: ${{ inputs.submodule_path }}
        run: cargo test --verbose
      
      - name: Check disk space
        run: df -h

      # Notify Slack
      - name: Notify Slack
        if: always()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "${{ job.status == 'success' && '✅' || '❌' }} *GitHub Action Result* for `${{ github.repository }}`",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*${{ github.workflow }}* job `${{ github.job }}` has *${{ job.status }}* :rocket:\n<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View full run>\n*PR Author:* ${{ github.event.pull_request.user.login }}\n*PR Link:* <${{ github.event.pull_request.html_url }}|View Pull Request>"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
